### ISSUE TITLE
Missing library

### ISSUE THREAD

**Issue by dariotarantini** [Szybet/InkWatchy#1]
I cannot compile the firmware, it miss the images.h header
```
In file included from src/main.cpp:1:
src/defines/defines.h:34:10: fatal error: images.h: No such file or directory

****************************************************************
* Looking for images.h dependency? Check our library registry!
```

**Comment by Szybet** [comment]
run the generate.sh file - it will convert images and fonts on the fly to header files which you are missing ;)

**Comment by Szybet** [comment]
added a few things to the readme about compiling

**Comment by dariotarantini** [comment]
hi, thank you. now i cant build fonts 😢 
./convertFonts.sh: riga 8: cd: ../../.pio/libdeps/watchy/Adafruit GFX Library/fontconvert/: File or directory doesnt exist

**Comment by Szybet** [comment]
Oh! let me fix that quickly, please wait ;)

**Comment by dariotarantini** [comment]
there is no such dependency. in pio folder

**Comment by Szybet** [comment]
I know, my fault im fixing that right now

**Comment by Szybet** [comment]
done, should work now with the latest commit

**Comment by dariotarantini** [comment]
missing book.txt :), maybe you should add some sample book

**Comment by dariotarantini** [comment]
also, unicode package should be installed. should be enough to run pip install unicode, but on my system  (arch) I used `sudo pacman -S python-unidecode`

**Comment by dariotarantini** [comment]
yeah missing book break compilation as well

**Comment by Szybet** [comment]
> missing book.txt :), maybe you should add some sample book

Nah, generating resources without book will fail, but if you disable book in config it will compile fine. It's in the readme

**Comment by Szybet** [comment]
> also, unicode package should be installed. should be enough to run pip install unicode, but on my system (arch) I used `sudo pacman -S python-unidecode`

you are free to edit the script and add your os dependent code to install it, contributions are welcome

**Comment by dariotarantini** [comment]
it worked! thank you man, really  a nice project. finally I can use my watchy as a kindle! 😄
