### ISSUE TITLE
misused this place for Q about KOBO image

### ISSUE THREAD

**Issue by Nifrabar** [Szybet/InkWatchy#14]
sorry to mis-use this place but I don't know how how to contact you.
I read on a forum you created a diskimage for the E-book reader KOBO nia.
I downloaded and tried to 'unzip' which failed......
Can I download somwhere a not compressed image?

Thanks for you help
-Bart
![szy](https://github.com/user-attachments/assets/c58f3944-f959-4435-9cae-c7798b291117)

**Comment by Szybet** [comment]
please send the link to this thread

also have you tried asking for the image other people? there is a thread for asking for images
