### ISSUE TITLE
"'initBatteryDebugDisplay' was not declared in this scope" compilling error, when DEBUG_MENUS=0

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [Szybet/InkWatchy#7]
```
Compiling .pio/build/min/src/ui/watchface/modules.cpp.o
src/ui/manager.cpp: In function 'void loopManager()':
src/ui/manager.cpp:126:41: error: 'initBatteryDebugDisplay' was not declared in this scope
         managerLaunchFunc(batteryDebug, initBatteryDebugDisplay, loopBatteryDebugDisplay);
                                         ^~~~~~~~~~~~~~~~~~~~~~~
src/ui/manager.cpp:126:41: note: suggested alternative: 'initGeneralDebugDisplay'
         managerLaunchFunc(batteryDebug, initBatteryDebugDisplay, loopBatteryDebugDisplay);
                                         ^~~~~~~~~~~~~~~~~~~~~~~
                                         initGeneralDebugDisplay
src/ui/manager.cpp:126:66: error: 'loopBatteryDebugDisplay' was not declared in this scope
         managerLaunchFunc(batteryDebug, initBatteryDebugDisplay, loopBatteryDebugDisplay);
                                                                  ^~~~~~~~~~~~~~~~~~~~~~~
Compiling .pio/build/min/src/ui/watchface/modulesDraw.cpp.o
Compiling .pio/build/min/src/ui/watchface/watchFaceDraw.cpp.o
src/ui/manager.cpp:126:66: note: suggested alternative: 'loopGeneralDebugDisplay'
         managerLaunchFunc(batteryDebug, initBatteryDebugDisplay, loopBatteryDebugDisplay);
                                                                  ^~~~~~~~~~~~~~~~~~~~~~~
                                                                  loopGeneralDebugDisplay
Compiling .pio/build/min/src/ui/watchface/watchFaceLogic.cpp.o
```
I had a compiling error on the stable e34f8529a960b9838434c077e5ca38ed commit version (Switched via a git hard reset and git clean), and when i had DEBUG_MENUS set to 0.

1. `git clone https://github.com/Szybet/InkWatchy`
2. `cd InkWatchy`
3. `git reset --hard e34f8529a960b9838434c077e5ca38ed && git clean -f`
4. `cd resources && ./generate.sh`
5. Edit `src/defines/config.h` according to :
	**- #define DEBUG_MENUS 0**
	- #define BITCOIN_MODULE 0
	- #define SMALL_BTC_MODULE 0
And edit `src/defines/confidential.h` as : 
	- #define WIFI_SSID1 "SSIDNAME"
	- #define WIFI_PASS1 "PASSWORD"
	- #define OPEN_WEATHER_API_KEY "APIKEY"
	- #define WEATHER_LATIT "LATTITUDE.WITHAPOINT"
	- #define WEATHER_LONGTIT "LONGITTUDE.WITHAPOINT"
	- #define WEATHER_LANG "TWOLETTERCOUNTRYISOCODE"
	- #define VAULT_PASSWORD "FOURNUMERICPINTHATDOESNTBEGINWITH0"
6. Go back to the root of the InkWatchy project (where the untouched platformio.ini resides)
7. `pio run`
The temporary solution I found to remedy this was to comment the debug options in `src/ui/manager.cpp` to prevent it to be compiled
https://github.com/Szybet/InkWatchy/blob/53ade7331f2fb2921b1a4b6d81e6d6a727d24298/src/ui/manager.cpp#L126

**Comment by Szybet** [comment]
fixed in https://github.com/Szybet/InkWatchy/commit/c842ba161c687a546eed3dccd5977d30cffb236c
